(() => {
  const $=id=>document.getElementById(id);
  const peso=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(n||0));
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalize=s=>String(s||'').trim().replace(/\s+/g,' ').toUpperCase();
  const manilaToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const num=(n,d=6)=>Number(n||0).toLocaleString('en-PH',{maximumFractionDigits:d});
  const state={status:null,user:null,catalog:null,category:'Coffee',query:'',cart:[],promoId:null,quote:null,inventory:[],report:null,costing:null,dashboard:null,adminProducts:[],adminIngredients:[],adminPromos:[],adminPackages:[],recipeRows:[],compositionRows:[],pendingSaleRequestId:null,checkoutBusy:false};
  const categories=['Coffee','Non Coffee','Food','Add-ons','Promos','Packages'];
  let quoteTimer=null,quoteSeq=0,recipeLoadSeq=0;

  function safeCloseDialog(id){const d=$(id);if(d?.open){try{d.close();}catch(_){}}}
  async function withFormLock(form,work){
    if(!form||form.dataset.busy==='1')return;
    form.dataset.busy='1';
    form.setAttribute('aria-busy','true');
    const controls=[...form.querySelectorAll('button,input,select,textarea')];
    const prior=controls.map(c=>({c,disabled:c.disabled,text:c.matches('button[type="submit"]')?c.textContent:null}));
    controls.forEach(c=>{c.disabled=true;if(c.matches('button[type="submit"]')&&c.textContent)c.textContent='Please wait…';});
    try{return await work();}
    finally{delete form.dataset.busy;form.removeAttribute('aria-busy');prior.forEach(({c,disabled,text})=>{c.disabled=disabled;if(text!==null)c.textContent=text;});}
  }
  const busyActions=new Set();
  async function withActionLock(key,work){
    if(busyActions.has(key))return;
    busyActions.add(key);
    try{return await work();}
    finally{busyActions.delete(key);}
  }
  function resetOrderState({render=true,resetSearch=true}={}){
    quoteSeq++;
    state.cart=[];state.promoId=null;state.quote=null;state.pendingSaleRequestId=null;state.checkoutBusy=false;
    state.category='Coffee';
    if(resetSearch){state.query='';if($('searchBox'))$('searchBox').value='';}
    if($('seniorEnabled'))$('seniorEnabled').checked=false;
    if($('seniorFields'))$('seniorFields').classList.add('hidden');
    if($('seniorName'))$('seniorName').value='';
    if($('seniorId'))$('seniorId').value='';
    if($('paymentMode'))$('paymentMode').value='Cash';
    if($('cashTender'))$('cashTender').value='';
    if($('gcashReference'))$('gcashReference').value='';
    if($('changePreview'))$('changePreview').textContent='Change: '+peso(0);
    if($('modalDue'))$('modalDue').textContent=peso(0);
    if($('quoteMessage'))$('quoteMessage').textContent='';
    if(render&&state.catalog)renderAll();
  }
  function enforceAddonLimits(){
    if(!state.catalog||!state.promoId)return;
    const c=cartCounts();
    state.cart=state.cart.filter(line=>{
      if(line.kind!=='addon')return true;
      const a=state.catalog.addOns.find(x=>x.id===line.id);if(!a)return false;
      const n=normalize(a.name),max=n==='FLAVORED FRIES'?c.food:n==='PREMIUM COFFEE'?c.coffee:line.qty;
      line.qty=Math.min(line.qty,Math.max(0,max));return line.qty>0;
    });
  }

  async function api(url,options={}){
    const controller=new AbortController();
    const timeoutMs=Number(options.timeoutMs||20000);
    const timer=setTimeout(()=>controller.abort(),timeoutMs);
    const opts={...options,signal:controller.signal,headers:{...(options.headers||{})}};
    delete opts.timeoutMs;
    if(options.body&&typeof options.body!=='string'){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(options.body);}
    try{
      const r=await fetch(url,opts);let data={};
      try{data=await r.json();}catch(_){if(!r.ok)data={error:`Server returned ${r.status} without a readable response.`};}
      if(r.status===401&&state.user){state.user=null;resetOrderState({render:false});showAuth(false);throw Object.assign(new Error('Your session expired. Please sign in again.'),{status:401});}
      if(!r.ok){const e=new Error(data.error||`Request failed (${r.status})`);e.status=r.status;e.details=data.details;throw e;}
      return data;
    }catch(err){
      if(err?.name==='AbortError')throw Object.assign(new Error('The POS server did not respond in time. Please retry.'),{status:0});
      if(err instanceof TypeError)throw Object.assign(new Error('Cannot reach the POS server. Keep the START COFFEE POS window open and retry.'),{status:0});
      throw err;
    }finally{clearTimeout(timer);}
  }
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),3500);}
  function showAuth(setupRequired){safeCloseDialog('paymentDialog');safeCloseDialog('receiptDialog');safeCloseDialog('transactionDialog');$('app').classList.add('hidden');$('authScreen').classList.remove('hidden');$('authTitle').textContent=setupRequired?'Create Web Admin':'Sign in';$('authHint').textContent=setupRequired?'First run: create a secure administrator account.':'Use your web POS account.';$('authSubmit').textContent=setupRequired?'Create Admin':'Sign in';$('authPassword').autocomplete=setupRequired?'new-password':'current-password';}
  function showApp(){$('authScreen').classList.add('hidden');$('app').classList.remove('hidden');$('currentUser').textContent=state.user.username;$('currentRole').textContent=state.user.role;document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',state.user.role!=='Admin'));$('dbEngine').textContent=(state.status?.engine||'database').toUpperCase();$('appVersion').textContent=state.status?.version||'FINAL';}
  async function boot(){
    state.status=await api('/api/status');
    if(state.status.setupRequired){resetOrderState({render:false});showAuth(true);return;}
    try{state.user=(await api('/api/auth/me')).user;}
    catch(err){if(err.status===401){state.user=null;resetOrderState({render:false});showAuth(false);return;}throw err;}
    resetOrderState({render:false});showApp();await loadCatalog();switchView('pos');
  }
  $('authForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{const username=$('authUsername').value.trim(),password=$('authPassword').value;try{if(state.status?.setupRequired){await api('/api/setup',{method:'POST',body:{username,password,active:true}});state.status=await api('/api/status');}state.user=(await api('/api/auth/login',{method:'POST',body:{username,password}})).user;resetOrderState({render:false});showApp();await loadCatalog();switchView('pos');$('authPassword').value='';toast(`Welcome, ${state.user.username}.`);}catch(err){toast(err.message);}});});
  $('logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});}catch(_){}state.user=null;resetOrderState({render:true});showAuth(false);};

  function switchView(view){
    document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));
    const titles={dashboard:['OPERATIONS','Dashboard'],pos:['POINT OF SALE','New Order'],inventory:['INVENTORY','Stock Management'],reports:['REPORTING','Sales & Costing Reports'],catalog:['ADMINISTRATION','Catalog & System Setup'],users:['ADMINISTRATION','User Accounts'],logs:['AUDIT','System Logs']};$('viewEyebrow').textContent=titles[view]?.[0]||'';$('viewTitle').textContent=titles[view]?.[1]||'';
    if(view==='dashboard')loadDashboard();if(view==='inventory')loadInventory();if(view==='reports')loadReport();if(view==='catalog')loadAdminAll();if(view==='users')loadUsers();if(view==='logs')loadLogs();
  }
  document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>switchView(n.dataset.view));

  function reconcileCartWithCatalog(){
    if(!state.catalog)return false;
    let changed=false;
    const productIds=new Set(state.catalog.products.map(x=>x.id)),addonIds=new Set(state.catalog.addOns.map(x=>x.id)),packageIds=new Set(state.catalog.packages.filter(x=>x.sellable&&!x.contents?.some(c=>c.active===false)).map(x=>x.id)),promoIds=new Set(state.catalog.promos.map(x=>x.id));
    const before=state.cart.length;
    state.cart=state.cart.filter(x=>x.kind==='product'?productIds.has(x.id):x.kind==='addon'?addonIds.has(x.id):x.kind==='package'?packageIds.has(x.id):false);
    if(state.cart.length!==before)changed=true;
    if(state.promoId&&!promoIds.has(state.promoId)){state.promoId=null;const n=state.cart.length;state.cart=state.cart.filter(x=>x.kind!=='addon');if(state.cart.length!==n)changed=true;changed=true;}
    const snapshot=JSON.stringify(state.cart);enforceAddonLimits();if(JSON.stringify(state.cart)!==snapshot)changed=true;
    if(changed)state.pendingSaleRequestId=null;
    return changed;
  }
  async function loadCatalog(){state.catalog=await api('/api/catalog');const changed=reconcileCartWithCatalog();renderTabs();renderPromo();renderCatalog();renderOrder();await refreshQuote();if(changed)toast('Order updated because a catalog item is no longer available.');}
  function renderTabs(){$('categoryTabs').innerHTML=categories.map(c=>`<button class="tab ${state.category===c?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$('categoryTabs').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderTabs();renderCatalog();});}
  function promoById(){return state.catalog?.promos.find(p=>p.id===state.promoId)||null;}
  function cartItem(kind,id){return state.cart.find(x=>x.kind===kind&&x.id===id);}
  function cartCounts(){let food=0,coffee=0;for(const x of state.cart){if(x.kind!=='product')continue;const p=state.catalog.products.find(p=>p.id===x.id);if(!p)continue;if(p.category==='Food')food+=x.qty;if(['Coffee','Non Coffee'].includes(p.category))coffee+=x.qty;}return{food,coffee};}
  function canAddProduct(p){const promo=promoById();if(!promo)return true;const c=cartCounts();if(p.category==='Food'&&c.food>=promo.foodLimit)return false;if(['Coffee','Non Coffee'].includes(p.category)&&c.coffee>=promo.coffeeLimit)return false;return true;}
  function canAddAddon(a){if(!state.promoId)return false;const c=cartCounts(),line=cartItem('addon',a.id),next=(line?.qty||0)+1,n=normalize(a.name);if(n==='FLAVORED FRIES'&&next>c.food)return false;if(n==='PREMIUM COFFEE'&&next>c.coffee)return false;return true;}
  function availabilityTip(item){
    if(!item)return'';const lines=[];
    if(item.availabilityStatus==='recipe_required')lines.push('RECIPE REQUIRED','Add at least one ingredient in Catalog Admin → Recipes before this item can be sold.');
    else if(item.availabilityStatus==='composition_required')lines.push('PACKAGE COMPOSITION REQUIRED','Add the package contents in Catalog Admin → Packages.');
    else if(item.availabilityStatus==='component_unavailable')lines.push('PACKAGE COMPONENT UNAVAILABLE');
    else if(item.available&&item.stockWarnings?.length)lines.push('LOW STOCK WARNING');
    else if(!item.available)lines.push('WHY THIS ITEM IS NOT AVAILABLE');
    for(const d of item.availabilityDetails||[]){
      if(d.message){lines.push(`• ${d.name}: ${d.message}`);continue;}
      const unit=d.uom?` ${d.uom}`:'';
      if(d.status==='ingredient_unavailable')lines.push(`• ${d.name}: ingredient is archived/unavailable`);
      else if(d.status==='out_of_stock')lines.push(`• ${d.name}: OUT OF STOCK — need ${num(d.required)}${unit}, current ${num(d.current)}${unit}`);
      else if(d.status==='low_stock')lines.push(`• ${d.name}: LOW/INSUFFICIENT — need ${num(d.required)}${unit}, current ${num(d.current)}${unit}, short ${num(d.shortage)}${unit}`);
    }
    for(const d of item.stockWarnings||[]){const unit=d.uom?` ${d.uom}`:'';lines.push(`• ${d.name}: low stock — current ${num(d.current)}${unit}, threshold ${num(d.threshold)}${unit}`);}
    return lines.join('\n');
  }
  function availabilityLabel(item){if(item.availabilityStatus==='recipe_required')return'RECIPE REQUIRED';if(item.availabilityStatus==='composition_required')return'COMPOSITION REQUIRED';if(item.availabilityStatus==='component_unavailable')return'COMPONENT UNAVAILABLE';if(!item.available)return'INSUFFICIENT INGREDIENT STOCK';if(item.stockWarnings?.length)return'LOW STOCK';return'';}
  function availabilityWrap(card,item){const tip=availabilityTip(item);if(!tip)return card;const attr=esc(tip).replace(/\n/g,'&#10;');return`<div class="availability-hover" tabindex="0" data-availability-tip="${attr}">${card}<span class="availability-hint" aria-hidden="true">ⓘ</span></div>`;}
  let availabilityTooltip=null;
  function ensureAvailabilityTooltip(){if(availabilityTooltip)return availabilityTooltip;availabilityTooltip=document.createElement('div');availabilityTooltip.className='availability-tooltip';availabilityTooltip.setAttribute('role','tooltip');document.body.appendChild(availabilityTooltip);return availabilityTooltip;}
  function showAvailabilityTooltip(el){const text=el?.dataset?.availabilityTip;if(!text)return;const tip=ensureAvailabilityTooltip();tip.textContent=text;tip.classList.add('show');const r=el.getBoundingClientRect(),w=tip.offsetWidth,h=tip.offsetHeight;let left=r.left+(r.width-w)/2;left=Math.max(8,Math.min(left,window.innerWidth-w-8));let top=r.top-h-10;if(top<8)top=Math.min(window.innerHeight-h-8,r.bottom+10);tip.style.left=`${Math.round(left)}px`;tip.style.top=`${Math.round(Math.max(8,top))}px`;}
  function hideAvailabilityTooltip(){availabilityTooltip?.classList.remove('show');}
  function bindAvailabilityTooltips(){document.querySelectorAll('#catalogGrid .availability-hover').forEach(el=>{el.addEventListener('mouseenter',()=>showAvailabilityTooltip(el));el.addEventListener('mouseleave',hideAvailabilityTooltip);el.addEventListener('focusin',()=>showAvailabilityTooltip(el));el.addEventListener('focusout',hideAvailabilityTooltip);});}
  function renderCatalog(){
    if(!state.catalog)return;hideAvailabilityTooltip();const q=normalize(state.query);let html='';
    if(state.category==='Promos'){const items=state.catalog.promos.filter(p=>!q||normalize(p.name).includes(q));html=items.map(p=>`<button class="product-card promo ${state.promoId===p.id?'selected':''}" data-promo="${p.id}"><div class="cat">PROMO · ${esc(p.inclusion)}</div><h4>${esc(p.name)}</h4><div class="price">${peso(p.price)}</div></button>`).join('');}
    else if(state.category==='Packages'){const items=state.catalog.packages.filter(p=>!q||normalize(p.name).includes(q));html=items.map(p=>{const enabled=p.sellable&&p.available&&!state.promoId;const label=state.promoId?'NOT ALLOWED WITH PROMO':availabilityLabel(p);const card=`<button class="product-card package" data-package="${p.id}" ${enabled?'':'disabled'}><div class="cat">PACKAGE · ${p.itemCount} ITEM TYPE(S)</div><h4>${esc(p.name)}</h4><div class="price">${p.sellable?peso(p.price):'Not Available'}</div>${label?`<div class="unavailable">${esc(label)}</div>`:''}</button>`;return state.promoId?card:availabilityWrap(card,p);}).join('');}
    else if(state.category==='Add-ons'){const items=state.catalog.addOns.filter(a=>!q||normalize(a.name).includes(q));html=items.map(a=>`<button class="product-card" data-addon="${a.id}" ${state.promoId?'':'disabled'}><div class="cat">PROMO UPGRADE · NO COSTING</div><h4>${esc(a.name)}</h4><div class="price">${peso(a.price)}</div>${state.promoId?'':'<div class="unavailable">PROMO ONLY</div>'}</button>`).join('');}
    else{const items=state.catalog.products.filter(p=>p.category===state.category&&(!q||normalize(p.name).includes(q)));html=items.map(p=>{const enabled=p.available&&canAddProduct(p),label=availabilityLabel(p);const card=`<button class="product-card ${p.stockWarnings?.length?'low-warning':''}" data-product="${p.id}" ${enabled?'':'disabled'}><div class="cat">${esc(p.category)}</div><h4>${esc(p.name)}</h4><div class="price">${p.available?peso(p.price):'Not Available'}</div>${label?`<div class="unavailable ${p.available?'warning':''}">${esc(label)}</div>`:''}</button>`;return availabilityWrap(card,p);}).join('');}
    $('catalogGrid').innerHTML=html||'<div class="empty-state"><div><b>No items found</b>Try another search.</div></div>';$('catalogGrid').querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addItem('product',Number(b.dataset.product)));$('catalogGrid').querySelectorAll('[data-addon]').forEach(b=>b.onclick=()=>addItem('addon',Number(b.dataset.addon)));$('catalogGrid').querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>addItem('package',Number(b.dataset.package)));$('catalogGrid').querySelectorAll('[data-promo]').forEach(b=>b.onclick=()=>selectPromo(Number(b.dataset.promo)));bindAvailabilityTooltips();
  }
  function selectPromo(id){if(state.promoId===id){cancelPromo();return;}if(state.cart.length&&!confirm('Selecting a promo will clear the current order. Continue?'))return;state.cart=[];state.promoId=id;$('seniorEnabled').checked=false;$('seniorFields').classList.add('hidden');$('seniorName').value='';$('seniorId').value='';state.pendingSaleRequestId=null;state.category='Coffee';renderAll();}
  function cancelPromo(){state.promoId=null;state.cart=[];state.pendingSaleRequestId=null;renderAll();}
  function addItem(kind,id){if(kind==='product'){const p=state.catalog.products.find(p=>p.id===id);if(!p)return;if(!p.available){toast(`${p.name} is not available. ${p.availabilityMessage||'Check its recipe and ingredient stock.'}`);return;}if(!canAddProduct(p)){toast('Promo item limit reached for this category.');return;}}if(kind==='package'){const p=state.catalog.packages.find(p=>p.id===id);if(!p?.sellable||!p.available){toast(`This package is not available. ${p?.availabilityMessage||'Check its composition and ingredient stock.'}`);return;}if(state.promoId){toast('Packages cannot be combined with a promo.');return;}}if(kind==='addon'){const a=state.catalog.addOns.find(a=>a.id===id);if(!a||!state.promoId){toast('This upgrade can only be used during a promo.');return;}if(!canAddAddon(a)){toast(`${a.name} cannot exceed the matching promo item quantity.`);return;}}const line=cartItem(kind,id);if(line)line.qty++;else state.cart.push({kind,id,qty:1});state.pendingSaleRequestId=null;renderAll();}
  function changeQty(kind,id,delta){const line=cartItem(kind,id);if(!line)return;if(delta>0&&kind==='product'){const p=state.catalog.products.find(p=>p.id===id);if(!p||!canAddProduct(p)){toast('Promo item limit reached.');return;}}if(delta>0&&kind==='addon'){const a=state.catalog.addOns.find(a=>a.id===id);if(!a||!canAddAddon(a)){toast('Upgrade quantity cannot exceed the matching promo item quantity.');return;}}line.qty+=delta;if(line.qty<=0)state.cart=state.cart.filter(x=>x!==line);if(delta<0&&kind==='product')enforceAddonLimits();state.pendingSaleRequestId=null;renderAll();}
  function clearCart(){resetOrderState();}
  function cartDisplayLine(x){if(x.kind==='product')return state.catalog.products.find(p=>p.id===x.id);if(x.kind==='addon')return state.catalog.addOns.find(a=>a.id===x.id);return state.catalog.packages.find(p=>p.id===x.id);}
  function localGross(){return state.cart.reduce((a,x)=>{const p=cartDisplayLine(x);return a+(p?Number(p.price)*x.qty:0);},0);}
  function renderOrder(){if(!state.cart.length){$('orderList').innerHTML='<div class="empty-state"><div><b>Your order is empty</b>Select an item to begin.</div></div>';return;}$('orderList').innerHTML=state.cart.map(x=>{const p=cartDisplayLine(x);if(!p)return'';return`<div class="order-row"><div><h4>${esc(p.name)}</h4><div class="row-sub">${x.kind==='addon'?'PROMO UPGRADE':x.kind==='package'?'PACKAGE':esc(p.category||'')} · ${peso(p.price)} each</div></div><div><strong>${peso(Number(p.price)*x.qty)}</strong><div class="qty-control"><button data-minus="${x.kind}:${x.id}">−</button><span>${x.qty}</span><button data-plus="${x.kind}:${x.id}">+</button></div></div></div>`;}).join('');$('orderList').querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const[k,id]=b.dataset.minus.split(':');changeQty(k,Number(id),-1);});$('orderList').querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const[k,id]=b.dataset.plus.split(':');changeQty(k,Number(id),1);});}
  function renderPromo(){const p=promoById();$('promoBanner').classList.toggle('hidden',!p);if(!p)return;const c=cartCounts();$('promoBanner').innerHTML=`<div><b>${esc(p.name)}</b> · Food ${c.food}/${p.foodLimit} · Coffee ${c.coffee}/${p.coffeeLimit} · Promo ${peso(p.price)} <span class="muted">(+ upgrades)</span></div><button id="cancelPromo">CANCEL PROMO</button>`;$('cancelPromo').onclick=cancelPromo;}
  function quotePayload(){return{items:state.cart.map(x=>({kind:x.kind,id:x.id,qty:x.qty})),promoId:state.promoId,senior:{enabled:$('seniorEnabled').checked,name:$('seniorName').value.trim(),id:$('seniorId').value.trim()}};}
  async function refreshQuote(){const seq=++quoteSeq,gross=localGross();$('grossAmount').textContent=peso(gross);$('payButton').disabled=true;state.quote=null;if(!state.cart.length){$('adjustmentAmount').textContent=peso(0);$('actualAmount').textContent=peso(0);$('payButton').textContent='Pay ₱0.00';$('quoteMessage').textContent='';return;}try{const quote=await api('/api/quote',{method:'POST',body:quotePayload()});if(seq!==quoteSeq)return;state.quote=quote;$('grossAmount').textContent=peso(quote.gross);$('adjustmentAmount').textContent=peso(quote.adjustment);$('actualAmount').textContent=peso(quote.actual);$('payButton').textContent=`Pay ${peso(quote.actual)}`;$('payButton').disabled=false;$('quoteMessage').textContent='';}catch(err){if(seq!==quoteSeq)return;$('adjustmentAmount').textContent='—';$('actualAmount').textContent='—';$('payButton').textContent='Complete Order';$('quoteMessage').textContent=err.message;if(err.status===409)await updateCatalogAvailability();}}
  function renderAll(){renderTabs();renderPromo();renderCatalog();renderOrder();clearTimeout(quoteTimer);quoteTimer=setTimeout(refreshQuote,80);}async function updateCatalogAvailability(){try{state.catalog=await api('/api/catalog');renderCatalog();}catch(_){}}
  $('searchBox').addEventListener('input',e=>{state.query=e.target.value;renderCatalog();});$('clearCart').onclick=clearCart;
  $('seniorEnabled').onchange=()=>{if($('seniorEnabled').checked&&state.promoId){$('seniorEnabled').checked=false;toast('Senior Citizen discount cannot be combined with a promo.');return;}$('seniorFields').classList.toggle('hidden',!$('seniorEnabled').checked);refreshQuote();};$('seniorName').oninput=()=>{clearTimeout(quoteTimer);quoteTimer=setTimeout(refreshQuote,300);};$('seniorId').oninput=()=>{clearTimeout(quoteTimer);quoteTimer=setTimeout(refreshQuote,300);};
  $('payButton').onclick=()=>{if(!state.quote||state.checkoutBusy)return;state.pendingSaleRequestId=state.pendingSaleRequestId||(globalThis.crypto?.randomUUID?.()||`sale-${Date.now()}-${Math.random().toString(36).slice(2)}`);$('paymentMode').value='Cash';$('cashTender').value=Number(state.quote.actual||0).toFixed(2);$('gcashReference').value='';renderPaymentFields();$('paymentDialog').showModal();};$('paymentClose').onclick=()=>{if(!state.checkoutBusy)$('paymentDialog').close();};$('paymentDialog').addEventListener('cancel',e=>{if(state.checkoutBusy)e.preventDefault();});$('paymentMode').onchange=renderPaymentFields;$('cashTender').oninput=renderPaymentFields;
  function renderPaymentFields(){const due=Number(state.quote?.actual||0),cash=$('paymentMode').value==='Cash';$('tenderWrap').classList.toggle('hidden',!cash);$('referenceWrap').classList.toggle('hidden',cash);if(cash&&!Number.isFinite(Number($('cashTender').value)))$('cashTender').value=due.toFixed(2);$('changePreview').textContent=cash?`Change: ${peso(Math.max(0,Number($('cashTender').value||0)-due))}`:'GCash payment: exact amount due';$('modalDue').textContent=peso(due);}
  $('paymentForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.quote||state.checkoutBusy)return;state.checkoutBusy=true;const submit=$('paymentSubmit'),close=$('paymentClose');if(submit){submit.disabled=true;submit.textContent='Processing…';}if(close)close.disabled=true;const payload={...quotePayload(),clientRequestId:state.pendingSaleRequestId||(globalThis.crypto?.randomUUID?.()||`sale-${Date.now()}-${Math.random().toString(36).slice(2)}`),paymentMode:$('paymentMode').value,tender:Number($('cashTender').value||0),paymentReference:$('gcashReference').value.trim()};state.pendingSaleRequestId=payload.clientRequestId;try{const sale=await api('/api/sales',{method:'POST',body:payload,timeoutMs:30000});$('paymentDialog').close();$('receiptText').textContent=`${sale.reference} · ${sale.paymentMode} · ${peso(sale.actual)}${sale.change?` · Change ${peso(sale.change)}`:''}${sale.idempotent?' · Safe retry recovered':''}`;resetOrderState({render:true});$('receiptDialog').showModal();try{await loadCatalog();}catch(refreshErr){console.error(refreshErr);toast('Sale recorded successfully. Catalog refresh will retry on the next action.');}}catch(err){toast(err.message);if(err.status===409)try{await loadCatalog();}catch(_){}}finally{state.checkoutBusy=false;if(submit){submit.disabled=false;submit.textContent='Confirm Payment';}if(close)close.disabled=false;}});$('receiptClose').onclick=()=>{$('receiptDialog').close();resetOrderState({render:true});$('searchBox')?.focus();};

  async function loadInventory(){try{state.inventory=(await api('/api/inventory')).items;renderInventory();await loadMovements();}catch(err){toast(err.message);}}
  function renderInventory(){const q=normalize($('inventorySearch').value),rows=state.inventory.filter(i=>!q||normalize(i.name).includes(q)||normalize(i.uom).includes(q)||normalize(i.code).includes(q));$('inventoryBody').innerHTML=rows.map(i=>`<tr><td><b>${esc(i.name)}</b><div class="tiny muted">${esc(i.code)}</div></td><td>${esc(String(i.uom).toUpperCase())}</td><td class="num">${num(i.stock)}</td><td class="num">${num(i.lowStockThreshold)}</td><td class="${i.low?'stock-low':'stock-ok'}">${i.low?'LOW':'OK'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No ingredients found.</td></tr>';const opts=state.inventory.map(i=>`<option value="${i.id}">${esc(i.name)} (${esc(String(i.uom).toUpperCase())})</option>`).join('');$('replenishIngredient').innerHTML=opts;$('transferIngredient').innerHTML=opts;}
  async function loadMovements(){try{const d=await api('/api/inventory/movements?limit=300');$('movementBody').innerHTML=d.items.map(x=>`<tr><td>${esc(formatDateTime(x.createdAt))}</td><td>${esc(x.type)}</td><td>${esc(x.ingredient)} <span class="tiny muted">${esc(String(x.uom).toUpperCase())}</span></td><td class="num ${x.quantityChange<0?'stock-low':'stock-ok'}">${x.quantityChange>0?'+':''}${num(x.quantityChange)}</td><td class="num">${num(x.balanceAfter)}</td><td>${esc(x.reference||x.branch||x.deliveredBy||'')}</td><td>${esc(x.createdBy||'')}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">No inventory movements.</td></tr>';}catch(err){toast(err.message);}}
  $('inventorySearch').oninput=renderInventory;$('refreshMovements').onclick=loadMovements;
  $('replenishForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{try{await api('/api/inventory/replenish',{method:'POST',body:{items:[{ingredientId:Number($('replenishIngredient').value),qty:Number($('replenishQty').value)}],deliveredBy:$('deliveredBy').value.trim(),remarks:$('replenishRemarks').value.trim()}});toast('Ingredients replenished successfully.');$('replenishQty').value='';await loadInventory();await loadCatalog();}catch(err){toast(err.message);}});});
  $('transferForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{try{await api('/api/inventory/transfer',{method:'POST',body:{items:[{ingredientId:Number($('transferIngredient').value),qty:Number($('transferQty').value)}],branch:$('transferBranch').value.trim(),receivedBy:$('receivedBy').value.trim(),remarks:$('transferRemarks').value.trim()}});toast('Transfer complete.');$('transferQty').value='';await loadInventory();await loadCatalog();}catch(err){toast(err.message);}});});

  function reportQuery(){const qs=new URLSearchParams({period:$('reportPeriod').value,date:$('reportDate').value||manilaToday()});if($('reportCashier').value.trim())qs.set('cashier',$('reportCashier').value.trim());return qs;}
  $('reportDate').value=manilaToday();
  async function loadReport(){if(!$('reportDate').value)$('reportDate').value=manilaToday();const qs=reportQuery();try{[state.report,state.costing]=await Promise.all([api(`/api/reports/sales?${qs}`),api(`/api/reports/costing?${qs}`)]);renderReport();renderCosting();}catch(err){toast(err.message);}}
  function renderReport(){const r=state.report;if(!r)return;$('reportSummary').innerHTML=[['Transactions',r.transactionCount],['Gross',peso(r.gross)],['Adjustment',peso(r.adjustment)],['Actual',peso(r.actual)],['Deleted',r.deletedCount]].map(([a,b])=>`<div class="summary-card"><span>${a}</span><strong>${b}</strong></div>`).join('');$('reportProducts').innerHTML=r.products.map(x=>`<tr><td>${esc(x.name)}${x.isAddOn?' <span class="badge">ADD-ON</span>':''}${x.isPackage?' <span class="badge">PACKAGE</span>':''}</td><td class="num">${num(x.qty,2)}</td><td class="num">${peso(x.gross)}</td><td class="num">${peso(x.adjusted)}</td><td class="num">${peso(x.actual)}</td><td class="num">${peso(x.costing)}</td><td class="num">${peso(x.net)}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">No sales for this period.</td></tr>';$('reportPromos').innerHTML=r.promos.map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${x.qty}</td><td class="num">${peso(x.gross)}</td><td class="num">${peso(x.adjustment)}</td><td class="num">${peso(x.actual)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No promo purchases for this period.</td></tr>';$('reportTransactions').innerHTML=r.transactions.map(x=>`<tr><td>${esc(x.reference)}</td><td>${esc(x.cashier||'')}</td><td class="${x.status==='Deleted'?'stock-low':'stock-ok'}">${esc(x.status)}</td><td>${esc(x.paymentMode||'')}</td><td>${esc(x.remark||'')}</td><td>${esc(formatDateTime(x.soldAt))}</td><td class="num">${peso(x.gross)}</td><td class="num">${peso(x.adjustment)}</td><td class="num">${peso(x.actual)}</td><td><button class="table-btn" data-view-sale="${encodeURIComponent(x.reference)}">View</button></td></tr>`).join('')||'<tr><td colspan="10" class="muted">No transaction logs.</td></tr>';$('reportTransactions').querySelectorAll('[data-view-sale]').forEach(b=>b.onclick=()=>viewTransaction(decodeURIComponent(b.dataset.viewSale)));}
  function renderCosting(){const r=state.costing;if(!r)return;$('costingTotal').textContent=`Total Cost: ${peso(r.totalCost)}`;$('costingList').innerHTML=r.ingredients.map(g=>`<details class="costing-group"><summary><div><b>${esc(g.name)}</b><span>${num(g.totalQty)} ${esc(String(g.uom).toUpperCase())}</span></div><strong>${peso(g.totalCost)}</strong></summary><div class="table-wrap"><table><thead><tr><th>Product</th><th class="num">Sold Qty</th><th class="num">Recipe Qty</th><th class="num">Total Usage</th><th class="num">Cost / Item</th><th class="num">Total Cost</th></tr></thead><tbody>${g.details.map(d=>`<tr><td>${esc(d.product)}</td><td class="num">${num(d.productQty,3)}</td><td class="num">${num(d.quantityRequired)}</td><td class="num">${num(d.usageQty)}</td><td class="num">${peso(d.costPerItem)}</td><td class="num">${peso(d.totalCost)}</td></tr>`).join('')}</tbody></table></div></details>`).join('')||'<div class="empty-state">No costed product sales for this period.</div>';}
  function transactionInfo(label,value,{money=false,wide=false}={}){const shown=value===null||value===undefined||value===''?'—':money?peso(value):esc(value);return`<div class="transaction-info ${wide?'wide':''}"><span>${esc(label)}</span><strong>${shown}</strong></div>`;}
  function renderTransactionDetail(d){
    $('transactionReference').textContent=d.reference||'Transaction Details';
    $('transactionStatus').textContent=d.status||'';$('transactionStatus').className=`transaction-status ${d.status==='Deleted'?'deleted':'sold'}`;
    const itemRows=(d.items||[]).map(i=>{const components=i.components?.length?`<div class="component-list"><b>Package contents:</b>${i.components.map(c=>`<span>${num(c.qty,2)} × ${esc(c.name)}</span>`).join('')}</div>`:'';return`<tr><td><b>${esc(i.name)}</b><div class="tiny muted">${esc(i.type)}${i.excludeFromCosting?' · Excluded from costing':''}</div>${components}</td><td class="num">${num(i.qty,2)}</td><td class="num">${peso(i.unitPrice)}</td><td class="num">${peso(i.lineTotal)}</td></tr>`;}).join('')||'<tr><td colspan="4" class="muted">No item lines were recorded.</td></tr>';
    const movementRows=(d.inventoryMovements||[]).map(m=>`<tr><td>${esc(formatDateTimeDetailed(m.createdAt))}</td><td>${esc(m.type)}</td><td>${esc(m.ingredient)}</td><td>${esc(String(m.uom||'').toUpperCase())}</td><td class="num ${m.quantityChange<0?'stock-low':'stock-ok'}">${m.quantityChange>0?'+':''}${num(m.quantityChange)}</td><td class="num">${m.balanceAfter==null?'—':num(m.balanceAfter)}</td><td>${esc(m.createdBy||'')}</td><td>${esc(m.remarks||'')}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">No web inventory movements were recorded for this transaction. Imported Excel transactions may not have per-sale stock movements.</td></tr>';
    const auditRows=(d.auditEvents||[]).map(e=>`<div class="audit-event"><div><b>${esc(e.status||'Event')}</b><span>${esc(formatDateTimeDetailed(e.createdAt))}</span></div><p>${esc(e.activity||'')}</p>${e.actor?`<small>Actor: ${esc(e.actor)}</small>`:''}${e.remark?`<small> · ${esc(e.remark)}</small>`:''}</div>`).join('')||'<div class="muted tiny">No matching system-log event was recorded.</div>';
    $('transactionDetailBody').innerHTML=`
      <div class="transaction-section"><h3>Transaction Information</h3><div class="transaction-info-grid">
        ${transactionInfo('Reference',d.reference)}${transactionInfo('Status',d.status)}${transactionInfo('Cashier',d.cashier)}${transactionInfo('Date / Time',formatDateTimeDetailed(d.soldAt))}
        ${transactionInfo('Payment Mode',d.paymentMode)}${transactionInfo('Payment Reference',d.paymentReference)}${transactionInfo('Cash Tender',d.tender,{money:true})}${transactionInfo('Change',d.change,{money:true})}
        ${transactionInfo('Promo',d.promo?.name)}${transactionInfo('Senior Citizen',d.seniorDetails)}${transactionInfo('Discount',d.discountAmount,{money:true})}${transactionInfo('Remark',d.remark,{wide:true})}
        ${d.deletedAt?transactionInfo('Deleted Date / Time',formatDateTimeDetailed(d.deletedAt)):''}${d.deletedAt?transactionInfo('Deleted By',d.deletedBy||'Unknown'):''}
      </div></div>
      <div class="transaction-section"><div class="transaction-section-head"><h3>Products Ordered</h3><span>${(d.items||[]).length} line(s)</span></div><div class="table-wrap"><table><thead><tr><th>Product / Item</th><th class="num">Qty</th><th class="num">Unit Price</th><th class="num">Line Total</th></tr></thead><tbody>${itemRows}</tbody></table></div></div>
      <div class="transaction-total-grid">${transactionInfo('Gross',d.gross,{money:true})}${transactionInfo('Adjustment',d.adjustment,{money:true})}${transactionInfo('Actual',d.actual,{money:true})}</div>
      <details class="transaction-section transaction-details"><summary>Inventory Impact <span>${(d.inventoryMovements||[]).length} movement(s)</span></summary><div class="table-wrap"><table><thead><tr><th>Date / Time</th><th>Type</th><th>Ingredient</th><th>UOM</th><th class="num">Change</th><th class="num">Balance</th><th>Actor</th><th>Remarks</th></tr></thead><tbody>${movementRows}</tbody></table></div></details>
      <details class="transaction-section transaction-details"><summary>Audit Events <span>${(d.auditEvents||[]).length} event(s)</span></summary><div class="audit-events">${auditRows}</div></details>`;
  }
  async function viewTransaction(reference){return withActionLock(`view-sale:${reference}`,async()=>{const dialog=$('transactionDialog');$('transactionReference').textContent=reference;$('transactionStatus').textContent='';$('transactionDetailBody').innerHTML='<div class="empty-state">Loading transaction details…</div>';if(!dialog.open)dialog.showModal();try{renderTransactionDetail(await api(`/api/sales/${encodeURIComponent(reference)}`));}catch(err){$('transactionDetailBody').innerHTML=`<div class="empty-state"><div><b>Unable to load transaction</b>${esc(err.message)}</div></div>`;toast(err.message);}});}
  $('transactionClose').onclick=()=>safeCloseDialog('transactionDialog');$('transactionDialog').addEventListener('click',e=>{if(e.target===$('transactionDialog'))safeCloseDialog('transactionDialog');});
  $('loadReport').onclick=loadReport;$('salesPdf').onclick=()=>window.open(`/api/reports/sales.pdf?${reportQuery()}`,'_blank');$('costingPdf').onclick=()=>window.open(`/api/reports/costing.pdf?${reportQuery()}`,'_blank');$('emailReport').onclick=()=>withActionLock('email-report',async()=>{try{const qs=Object.fromEntries(reportQuery());const d=await api('/api/reports/email',{method:'POST',body:qs,timeoutMs:60000});toast(`Report emailed to ${d.to}.`);}catch(err){toast(err.message);}});

  async function loadDashboard(){try{state.dashboard=await api('/api/dashboard');renderDashboard();}catch(err){toast(err.message);}}
  function renderDashboard(){const d=state.dashboard;if(!d)return;$('dashboardSummary').innerHTML=[['Today Actual',peso(d.metrics.todayActual)],['Today Gross',peso(d.metrics.todayGross)],['Today Transactions',d.metrics.todayTransactions],['Month Actual',peso(d.metrics.monthActual)],['Low Stock',d.metrics.lowStockCount]].map(([a,b])=>`<div class="summary-card"><span>${a}</span><strong>${b}</strong></div>`).join('');$('dashboardLowStock').innerHTML=d.lowStock.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(String(x.uom).toUpperCase())}</td><td class="num stock-low">${num(x.stock)}</td><td class="num">${num(x.lowStockThreshold)}</td></tr>`).join('')||'<tr><td colspan="4" class="stock-ok">No low-stock ingredients.</td></tr>';const max=Math.max(1,...d.categorySales.map(x=>x.amount));$('categorySales').innerHTML=d.categorySales.map(x=>`<div class="bar-row"><div><b>${esc(x.name)}</b><span>${peso(x.amount)}</span></div><div class="bar-track"><i style="width:${Math.max(2,x.amount/max*100)}%"></i></div></div>`).join('')||'<div class="empty-state">No sales this month.</div>';drawLineChart($('salesTrendChart'),d.trend.map(x=>x.actual),d.trend.map(x=>x.date.slice(5)));drawBarChart($('topProductsChart'),d.topProducts.map(x=>x.qty),d.topProducts.map(x=>x.name));}
  function setupCanvas(canvas){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.max(300,rect.width)*ratio;canvas.height=250*ratio;const c=canvas.getContext('2d');c.setTransform(ratio,0,0,ratio,0,0);return{c,w:Math.max(300,rect.width),h:250};}
  function drawLineChart(canvas,values,labels){const{c,w,h}=setupCanvas(canvas);c.clearRect(0,0,w,h);const pad=32,max=Math.max(1,...values),step=(w-pad*2)/Math.max(1,values.length-1);c.strokeStyle='#d9ddd9';c.lineWidth=1;for(let i=0;i<4;i++){const y=pad+(h-pad*2)*i/3;c.beginPath();c.moveTo(pad,y);c.lineTo(w-pad,y);c.stroke();}c.strokeStyle='#1f5a43';c.lineWidth=2.5;c.beginPath();values.forEach((v,i)=>{const x=pad+i*step,y=h-pad-(h-pad*2)*v/max;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();c.fillStyle='#6b746f';c.font='10px system-ui';for(let i=0;i<labels.length;i+=Math.max(1,Math.ceil(labels.length/6)))c.fillText(labels[i],pad+i*step-10,h-8);}
  function drawBarChart(canvas,values,labels){const{c,w,h}=setupCanvas(canvas);c.clearRect(0,0,w,h);const max=Math.max(1,...values),pad=16,row=(h-pad*2)/Math.max(1,values.length);c.font='10px system-ui';values.forEach((v,i)=>{const y=pad+i*row,label=String(labels[i]||'').slice(0,22);c.fillStyle='#50615a';c.fillText(label,pad,y+11);c.fillStyle='#e3ece7';c.fillRect(pad,y+16,w-pad*2,row-22);c.fillStyle='#1f5a43';c.fillRect(pad,y+16,(w-pad*2)*v/max,row-22);c.fillStyle='#17231e';c.fillText(num(v,1),w-pad-28,y+11);});}
  $('dashboardRefresh').onclick=loadDashboard;

  function activateAdminTab(tab){document.querySelectorAll('#adminTabs button').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===tab));document.querySelectorAll('.admin-panel').forEach(p=>p.classList.toggle('active',p.id===`admin-${tab}`));if(tab==='recipes')loadRecipe();if(tab==='settings')loadSettings();if(tab==='backups')loadBackups();}
  document.querySelectorAll('#adminTabs button').forEach(b=>b.onclick=()=>activateAdminTab(b.dataset.adminTab));
  async function loadAdminAll(){if(state.user?.role!=='Admin')return;try{const selectedRecipe=$('recipeProduct').value,selectedPackage=$('compositionPackage').value;const [p,i,pr,pa]=await Promise.all([api('/api/admin/products'),api('/api/admin/ingredients'),api('/api/admin/promos'),api('/api/admin/packages')]);state.adminProducts=p.products;state.adminIngredients=i.ingredients;state.adminPromos=pr.promos;state.adminPackages=pa.packages;renderAdminProducts();renderAdminIngredients();renderAdminPromos();renderAdminPackages();fillAdminSelects(selectedRecipe,selectedPackage);}catch(err){toast(err.message);}}
  function fillAdminSelects(selectedRecipe='',selectedPackage=''){const activeProducts=state.adminProducts.filter(x=>x.active),productOpts=activeProducts.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('recipeProduct').innerHTML=productOpts;$('compositionProduct').innerHTML=productOpts;const ingOpts=state.adminIngredients.filter(x=>x.active).map(i=>`<option value="${i.id}">${esc(i.name)} (${esc(String(i.uom).toUpperCase())})</option>`).join('');$('recipeIngredient').innerHTML=ingOpts;$('compositionPackage').innerHTML=state.adminPackages.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(selectedRecipe&&activeProducts.some(p=>String(p.id)===String(selectedRecipe)))$('recipeProduct').value=String(selectedRecipe);if(selectedPackage&&state.adminPackages.some(p=>String(p.id)===String(selectedPackage)))$('compositionPackage').value=String(selectedPackage);if(activeProducts.length)loadRecipe();else{state.recipeRows=[];renderRecipe();}if(state.adminPackages.length)loadComposition();else{state.compositionRows=[];renderComposition();}}

  function renderAdminProducts(){const q=normalize($('adminProductSearch').value),rows=state.adminProducts.filter(p=>!q||normalize(p.name).includes(q)||normalize(p.category).includes(q));$('adminProductsBody').innerHTML=rows.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="tiny muted">${esc(p.sku)}</div></td><td>${esc(p.category)}</td><td class="num">${peso(p.price)}</td><td class="num">${peso(p.unitCost)}</td><td class="${p.active&&!p.recipeCount?'stock-low':''}">${p.recipeCount} ingredient(s)${p.active&&!p.recipeCount?'<div class="tiny">RECIPE REQUIRED · NOT SELLABLE</div>':''}</td><td class="${p.active?'stock-ok':'stock-low'}">${p.active?'ACTIVE':'ARCHIVED'}</td><td><button class="table-btn" data-edit-product="${p.id}">Edit</button>${p.active?`<button class="danger-link" data-archive-product="${p.id}">Archive</button>`:''}</td></tr>`).join('');$('adminProductsBody').querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(Number(b.dataset.editProduct)));$('adminProductsBody').querySelectorAll('[data-archive-product]').forEach(b=>b.onclick=()=>archiveProduct(Number(b.dataset.archiveProduct)));}
  $('adminProductSearch').oninput=renderAdminProducts;
  function clearProductForm(){$('productEditId').value='';$('productName').value='';$('productName').readOnly=false;$('productCategory').value='Coffee';$('productPrice').value='';$('productActive').checked=true;$('productFormTitle').textContent='New Product';}
  function editProduct(id){const p=state.adminProducts.find(x=>x.id===id);if(!p)return;$('productEditId').value=id;$('productName').value=p.name;$('productName').readOnly=true;$('productCategory').value=p.category;$('productPrice').value=p.price;$('productActive').checked=p.active;$('productFormTitle').textContent=`Update ${p.name}`;}
  async function archiveProduct(id){return withActionLock(`archive-product:${id}`,async()=>{const p=state.adminProducts.find(x=>x.id===id);if(!p||!confirm(`Archive ${p.name}? It will disappear from the POS but historical sales remain.`))return;try{await api(`/api/admin/products/${id}`,{method:'DELETE'});toast('Product archived.');await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});}
  $('productFormClear').onclick=clearProductForm;$('productForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{const id=Number($('productEditId').value||0),body={name:$('productName').value.trim(),category:$('productCategory').value,price:Number($('productPrice').value),active:$('productActive').checked};try{if(id)await api(`/api/admin/products/${id}`,{method:'PUT',body});else await api('/api/admin/products',{method:'POST',body});toast(id?'Product updated.':'Product added. It will stay Not Available until recipe ingredients are added.');clearProductForm();await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});});

  function renderAdminIngredients(){const q=normalize($('adminIngredientSearch').value),rows=state.adminIngredients.filter(i=>!q||normalize(i.name).includes(q)||normalize(i.code).includes(q)||normalize(i.uom).includes(q));$('adminIngredientsBody').innerHTML=rows.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td class="tiny">${esc(i.code)}</td><td>${esc(String(i.uom).toUpperCase())}</td><td class="num">${num(i.stock)}</td><td class="num">${num(i.lowStockThreshold)}</td><td class="${i.active?'stock-ok':'stock-low'}">${i.active?'ACTIVE':'ARCHIVED'}</td><td><button class="table-btn" data-edit-ing="${i.id}">Edit</button>${i.active?`<button class="danger-link" data-archive-ing="${i.id}">Archive</button>`:''}</td></tr>`).join('');$('adminIngredientsBody').querySelectorAll('[data-edit-ing]').forEach(b=>b.onclick=()=>editIngredient(Number(b.dataset.editIng)));$('adminIngredientsBody').querySelectorAll('[data-archive-ing]').forEach(b=>b.onclick=()=>archiveIngredient(Number(b.dataset.archiveIng)));}
  $('adminIngredientSearch').oninput=renderAdminIngredients;
  function clearIngredientForm(){$('ingredientEditId').value='';$('ingredientName').value='';$('ingredientUom').value='';$('ingredientThreshold').value='0';$('ingredientActive').checked=true;$('ingredientFormTitle').textContent='New Ingredient';}
  function editIngredient(id){const i=state.adminIngredients.find(x=>x.id===id);if(!i)return;$('ingredientEditId').value=id;$('ingredientName').value=i.name;$('ingredientUom').value=i.uom;$('ingredientThreshold').value=i.lowStockThreshold;$('ingredientActive').checked=i.active;$('ingredientFormTitle').textContent=`Update ${i.name}`;}
  async function archiveIngredient(id){return withActionLock(`archive-ingredient:${id}`,async()=>{const i=state.adminIngredients.find(x=>x.id===id);if(!i||!confirm(`Archive ${i.name}? This is allowed only when no recipe uses it.`))return;try{await api(`/api/admin/ingredients/${id}`,{method:'DELETE'});toast('Ingredient archived.');await loadAdminAll();await loadInventory();await loadCatalog();}catch(err){toast(err.message);}});}
  $('ingredientFormClear').onclick=clearIngredientForm;$('ingredientForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{const id=Number($('ingredientEditId').value||0),body={name:$('ingredientName').value.trim(),uom:$('ingredientUom').value.trim(),lowStockThreshold:Number($('ingredientThreshold').value||0),active:$('ingredientActive').checked};try{if(id)await api(`/api/admin/ingredients/${id}`,{method:'PUT',body});else await api('/api/admin/ingredients',{method:'POST',body});toast(id?'Ingredient updated.':'Ingredient added.');clearIngredientForm();await loadAdminAll();await loadInventory();await loadCatalog();}catch(err){toast(err.message);}});});

  async function loadRecipe(){const id=Number($('recipeProduct').value||state.adminProducts.find(x=>x.active)?.id||0);if(!id){state.recipeRows=[];renderRecipe();return;}const seq=++recipeLoadSeq;try{const d=await api(`/api/admin/products/${id}/recipe`);if(seq!==recipeLoadSeq||Number($('recipeProduct').value)!==id)return;state.recipeRows=d.items.map(x=>({...x}));renderRecipe();}catch(err){if(seq===recipeLoadSeq)toast(err.message);}}
  function renderRecipe(){$('recipeBody').innerHTML=state.recipeRows.map((r,i)=>`<tr><td>${esc(r.name)}</td><td>${esc(String(r.uom).toUpperCase())}</td><td class="num">${num(r.quantity)}</td><td class="num">${r.cost===null?'—':peso(r.cost)}</td><td><button class="danger-link" data-remove-recipe="${i}">Remove</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No recipe rows. This product stays Not Available until at least one ingredient is added and saved.</td></tr>';$('recipeBody').querySelectorAll('[data-remove-recipe]').forEach(b=>b.onclick=()=>{state.recipeRows.splice(Number(b.dataset.removeRecipe),1);renderRecipe();});$('recipeUnitCost').textContent=`Unit Cost: ${peso(state.recipeRows.reduce((a,x)=>a+Number(x.cost||0),0))}`;}
  $('recipeProduct').onchange=loadRecipe;$('recipeAdd').onclick=()=>{const iid=Number($('recipeIngredient').value),ing=state.adminIngredients.find(x=>x.id===iid),qty=Number($('recipeQty').value),cost=$('recipeCost').value===''?null:Number($('recipeCost').value);if(!ing||!Number.isFinite(qty)||!(qty>0)||cost!==null&&(!Number.isFinite(cost)||cost<0)){toast('Choose an ingredient, quantity greater than zero, and optional non-negative cost.');return;}const existing=state.recipeRows.find(x=>x.ingredientId===iid);const row={ingredientId:iid,code:ing.code,name:ing.name,uom:ing.uom,quantity:qty,cost};if(existing)Object.assign(existing,row);else state.recipeRows.push(row);$('recipeQty').value='';$('recipeCost').value='';renderRecipe();};$('saveRecipe').onclick=()=>withActionLock('save-recipe',async()=>{const pid=Number($('recipeProduct').value);if(!pid){toast('Choose a product first.');return;}try{await api(`/api/admin/products/${pid}/recipe`,{method:'PUT',body:{items:state.recipeRows.map(x=>({ingredientId:x.ingredientId,quantity:x.quantity,cost:x.cost}))}});toast('Recipe and costing saved.');await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});

  function renderAdminPromos(){$('adminPromosBody').innerHTML=state.adminPromos.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.inclusion)}</td><td class="num">${peso(p.price)}</td><td>${p.foodLimit} Food / ${p.coffeeLimit} Coffee</td><td class="${p.active?'stock-ok':'stock-low'}">${p.active?'ACTIVE':'DISABLED'}</td><td><button class="table-btn" data-edit-promo="${p.id}">Edit</button>${p.active?`<button class="danger-link" data-archive-promo="${p.id}">Disable</button>`:''}</td></tr>`).join('');$('adminPromosBody').querySelectorAll('[data-edit-promo]').forEach(b=>b.onclick=()=>editPromo(Number(b.dataset.editPromo)));$('adminPromosBody').querySelectorAll('[data-archive-promo]').forEach(b=>b.onclick=()=>archivePromo(Number(b.dataset.archivePromo)));}
  function clearPromoForm(){$('promoEditId').value='';$('promoName').value='';$('promoInclusion').value='';$('promoPrice').value='';$('promoFood').value='';$('promoCoffee').value='';$('promoActive').checked=true;}
  function editPromo(id){const p=state.adminPromos.find(x=>x.id===id);if(!p)return;$('promoEditId').value=id;$('promoName').value=p.name;$('promoInclusion').value=p.inclusion;$('promoPrice').value=p.price;$('promoFood').value=p.foodLimit;$('promoCoffee').value=p.coffeeLimit;$('promoActive').checked=p.active;}
  async function archivePromo(id){return withActionLock(`archive-promo:${id}`,async()=>{const p=state.adminPromos.find(x=>x.id===id);if(!p||!confirm(`Disable ${p.name}?`))return;try{await api(`/api/admin/promos/${id}`,{method:'DELETE'});toast('Promo disabled.');await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});}
  $('promoFormClear').onclick=clearPromoForm;$('promoForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{const id=Number($('promoEditId').value||0),body={name:$('promoName').value.trim(),inclusion:$('promoInclusion').value.trim(),price:Number($('promoPrice').value),foodLimit:Number($('promoFood').value),coffeeLimit:Number($('promoCoffee').value),active:$('promoActive').checked};try{if(id)await api(`/api/admin/promos/${id}`,{method:'PUT',body});else await api('/api/admin/promos',{method:'POST',body});toast(id?'Promo updated.':'Promo added.');clearPromoForm();await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});});

  function renderAdminPackages(){$('adminPackagesBody').innerHTML=state.adminPackages.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td class="num">${peso(p.price)}</td><td>${p.items.length?`${p.items.length} product type(s)`:'<span class="stock-low">REQUIRED</span>'}</td><td class="${p.active?'stock-ok':'stock-low'}">${p.active?'ACTIVE':'DISABLED'}</td><td><button class="table-btn" data-edit-package="${p.id}">Edit</button>${p.active?`<button class="danger-link" data-archive-package="${p.id}">Disable</button>`:''}</td></tr>`).join('');$('adminPackagesBody').querySelectorAll('[data-edit-package]').forEach(b=>b.onclick=()=>editPackage(Number(b.dataset.editPackage)));$('adminPackagesBody').querySelectorAll('[data-archive-package]').forEach(b=>b.onclick=()=>archivePackage(Number(b.dataset.archivePackage)));}
  function clearPackageForm(){$('packageEditId').value='';$('packageName').value='';$('packagePrice').value='';$('packageActive').checked=true;}
  function editPackage(id){const p=state.adminPackages.find(x=>x.id===id);if(!p)return;$('packageEditId').value=id;$('packageName').value=p.name;$('packagePrice').value=p.price;$('packageActive').checked=p.active;$('compositionPackage').value=String(id);loadComposition();}
  async function archivePackage(id){return withActionLock(`archive-package:${id}`,async()=>{const p=state.adminPackages.find(x=>x.id===id);if(!p||!confirm(`Disable ${p.name}?`))return;try{await api(`/api/admin/packages/${id}`,{method:'DELETE'});toast('Package disabled.');await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});}
  $('packageFormClear').onclick=clearPackageForm;$('packageForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{const id=Number($('packageEditId').value||0),body={name:$('packageName').value.trim(),price:Number($('packagePrice').value),active:$('packageActive').checked};try{if(id)await api(`/api/admin/packages/${id}`,{method:'PUT',body});else await api('/api/admin/packages',{method:'POST',body});toast(id?'Package updated.':'Package added.');clearPackageForm();await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});});
  function loadComposition(){const id=Number($('compositionPackage').value),p=state.adminPackages.find(x=>x.id===id);state.compositionRows=(p?.items||[]).map(x=>({...x}));renderComposition();}
  function renderComposition(){$('compositionList').innerHTML=state.compositionRows.map((r,i)=>`<div class="mini-row"><span><b>${esc(r.name)}</b> × ${num(r.qty,2)}</span><button class="danger-link" data-remove-comp="${i}">Remove</button></div>`).join('')||'<div class="muted tiny">No products assigned yet.</div>';$('compositionList').querySelectorAll('[data-remove-comp]').forEach(b=>b.onclick=()=>{state.compositionRows.splice(Number(b.dataset.removeComp),1);renderComposition();});}
  $('compositionPackage').onchange=loadComposition;$('compositionAdd').onclick=()=>{const pid=Number($('compositionProduct').value),p=state.adminProducts.find(x=>x.id===pid),qty=Number($('compositionQty').value);if(!p||!Number.isInteger(qty)||!(qty>0)){toast('Choose a product and a positive whole-number quantity.');return;}const existing=state.compositionRows.find(x=>x.productId===pid),row={productId:pid,name:p.name,qty};if(existing)Object.assign(existing,row);else state.compositionRows.push(row);$('compositionQty').value='';renderComposition();};$('saveComposition').onclick=()=>withActionLock('save-composition',async()=>{const id=Number($('compositionPackage').value);if(!id){toast('Choose a package first.');return;}try{await api(`/api/admin/packages/${id}/items`,{method:'PUT',body:{items:state.compositionRows.map(x=>({productId:x.productId,qty:x.qty}))}});toast('Package composition saved.');await loadAdminAll();await loadCatalog();}catch(err){toast(err.message);}});

  async function loadSettings(){try{const s=await api('/api/admin/settings');$('shopName').value=s.shopName||'';$('defaultReportEmail').value=s.defaultReportEmail||'';$('smtpStatus').innerHTML=`<b class="${s.smtp.configured?'stock-ok':'stock-low'}">${s.smtp.configured?'CONFIGURED':'NOT CONFIGURED'}</b><br>Host: ${esc(s.smtp.host)}:${s.smtp.port}<br>User: ${esc(s.smtp.user||'—')}<br><span class="tiny muted">Set SMTP_USER and SMTP_PASS on the server. Gmail App Passwords are supported over TLS port 465.</span>`;}catch(err){toast(err.message);}}
  $('settingsForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{try{await api('/api/admin/settings',{method:'PUT',body:{shopName:$('shopName').value.trim(),defaultReportEmail:$('defaultReportEmail').value.trim()}});toast('Settings saved.');await loadSettings();}catch(err){toast(err.message);}});});

  async function loadBackups(){try{const d=await api('/api/backups');$('backupNote').textContent=d.supported?'SQLite backups are stored on the server. One automatic backup is created daily and up to 30 automatic backups are retained.':d.note;$('createBackup').disabled=!d.supported;$('backupBody').innerHTML=d.items.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(formatDateTime(x.createdAt))}</td><td class="num">${(x.size/1024).toFixed(1)} KB</td><td><a class="table-btn" href="/api/backups/${encodeURIComponent(x.name)}">Download</a> <button class="danger-link" data-restore="${esc(x.name)}">Restore</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">No backups yet.</td></tr>';$('backupBody').querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>restoreBackup(b.dataset.restore));}catch(err){toast(err.message);}}
  $('createBackup').onclick=()=>withActionLock('create-backup',async()=>{try{const d=await api('/api/backups',{method:'POST',timeoutMs:60000});toast(`Backup created: ${d.name}`);await loadBackups();}catch(err){toast(err.message);}});
  async function restoreBackup(name){return withActionLock(`restore-backup:${name}`,async()=>{if(!confirm(`Restore ${name}? This will replace the current SQLite database.`))return;if(!confirm('Final warning: a pre-restore backup will be created automatically. Continue with restore?'))return;try{await api(`/api/backups/${encodeURIComponent(name)}/restore`,{method:'POST',timeoutMs:60000});alert('Database restored. Please sign in again.');location.reload();}catch(err){toast(err.message);}});}

  async function loadUsers(){if(state.user?.role!=='Admin')return;try{const d=await api('/api/users');$('usersBody').innerHTML=d.users.map(u=>`<tr><td><b>${esc(u.username)}</b></td><td>${esc(u.role)}</td><td class="${u.active?'stock-ok':'stock-low'}">${u.active?'ACTIVE':'INACTIVE'}</td><td>${u.hasWebPassword?'SET':'RESET REQUIRED'}</td><td><button class="table-btn" data-edit-user="${u.id}">Edit</button></td></tr>`).join('');$('usersBody').querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>editUser(Number(b.dataset.editUser),d.users));}catch(err){toast(err.message);}}
  function clearUserForm(){$('userEditId').value='';$('newUsername').value='';$('newUsername').readOnly=false;$('newPassword').value='';$('newPassword').required=true;$('newRole').value='User';$('newUserActive').checked=true;}
  function editUser(id,users){const u=users.find(x=>x.id===id);if(!u)return;$('userEditId').value=id;$('newUsername').value=u.username;$('newUsername').readOnly=true;$('newPassword').value='';$('newPassword').required=false;$('newRole').value=u.role;$('newUserActive').checked=u.active;}
  $('userFormClear').onclick=clearUserForm;$('userForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;await withFormLock(form,async()=>{const id=Number($('userEditId').value||0),body={username:$('newUsername').value.trim(),password:$('newPassword').value,role:$('newRole').value,active:$('newUserActive').checked};try{if(id)await api(`/api/users/${id}`,{method:'PUT',body});else await api('/api/users',{method:'POST',body});toast('User account saved.');clearUserForm();await loadUsers();}catch(err){toast(err.message);}});});

  function formatDateTime(v){if(!v)return'';const s=String(v);if(!/[zZ]|[+-]\d\d:\d\d$/.test(s))return s.replace('T',' ');const d=new Date(s);return new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'}).format(d);}
  function formatDateTimeDetailed(v){if(!v)return'';const s=String(v);if(!/[zZ]|[+-]\d\d:\d\d$/.test(s))return s.replace('T',' ');const d=new Date(s);return new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'medium'}).format(d);}
  async function loadLogs(){try{const d=await api('/api/system-logs?limit=500');$('logsList').innerHTML=d.logs.map(l=>`<div class="log-row"><div class="log-meta"><b>${esc(l.status||'LOG')}</b><span>${esc(l.actor||'')}</span><span>${esc(formatDateTime(l.createdAt))}</span>${l.remark?`<span>· ${esc(l.remark)}</span>`:''}</div><pre>${esc(l.activity)}</pre></div>`).join('')||'<div class="empty-state">No system logs.</div>';}catch(err){toast(err.message);}}
  $('refreshLogs').onclick=loadLogs;

  window.addEventListener('resize',()=>{if(state.dashboard)renderDashboard();});
  setInterval(()=>$('clock').textContent=new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date()),1000);
  boot().catch(err=>{console.error(err);toast(err.message||'Unable to start the POS.');showAuth(false);$('authHint').textContent='Cannot reach the POS server. Keep START COFFEE POS open, then refresh this page.';});
})();
